---
- name: Install flatpak apps
  community.general.flatpak:
    name: '{{ item }}'
    state: present
  loop: '{{ flatpaks }}'
  become: true

- name: Install Desktop apps
  ansible.builtin.dnf:
    name: '{{ item }}'
    state: present
  loop: '{{ desktop_apps }}'
  become: true

- name: Config Alacritty 
  ansible.builtin.copy:
    src: '{{ role_path }}/files/alacritty/'
    dest: '~/.config/alacritty/'

- name: Create ghostty config dir
  ansible.builtin.file:
    path: ~/.config/ghostty
    state: directory
    mode: '0755'

- name: Config ghostty
  ansible.builtin.copy:
    src: '{{ role_path }}/files/ghostty/config'
    dest: '~/.config/ghostty'
    mode: '644'
