---
- name: Install flatpak apps
  community.general.flatpak:
    name: '{{ item }}'
    state: present
  loop: '{{ flatpaks }}'
  become: true

- name: Install vscode repo
  become: true
  ansible.builtin.yum_repository:
    name: code
    description: Visual Studio Code
    file: vscode
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    enabled: true
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    gpgcheck: true

- name: Enable ghostty COPR repository
  community.general.copr:
    state: enabled
    name: scottames/ghostty
  become: true

- name: Install Desktop apps
  ansible.builtin.dnf:
    name: '{{ item }}'
    state: present
  loop: '{{ desktop_apps }}'
  become: true

- name: Config Alacritty 
  ansible.builtin.copy:
    src: '{{ role_path }}/files/alacritty/'
    dest: '~/.config/alacritty/'

- name: Create ghostty config dir
  ansible.builtin.file:
    path: ~/.config/ghostty
    state: directory
    mode: '0755'

- name: Config ghostty
  ansible.builtin.copy:
    src: '{{ role_path }}/files/ghostty/config'
    dest: '~/.config/ghostty'
    mode: '644'
