---
- name: Add docker repository
  become: true
  ansible.builtin.command: dnf config-manager addrepo --from-repofile=https://download.docker.com/linux/fedora/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo

- name: Install docker packages
  become: true
  ansible.builtin.dnf:
    name: '{{ item }}'
    state: present
  loop: '{{ docker_packages }}'

- name: Enable docker service
  become: true
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Ensure group docker exists
  become: true
  ansible.builtin.group:
    name: docker
    state: present

- name: Append the group docker to user
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
