---
- name: Create fonts dir
  ansible.builtin.file:
    path: ~/.local/share/fonts
    state: directory
    mode: '0755'

- name: Install Jetbrains Nerd Fonts
  ansible.builtin.unarchive:
    src: '{{ role_path }}/files/fonts/jetbrains-nerd-font-mono.zip'
    dest: ~/.local/share/fonts
