---
- name: Check if WhiteSur icon theme is installed
  ansible.builtin.stat:
    path: /usr/share/icons/WhiteSur
  register: whitesur_dir

- name: Confirm reinstallation of icon theme
  ansible.builtin.pause:
    prompt: Reinstall WhiteSur icon theme?(Y/N)
    echo: true
  when: whitesur_dir.stat.exists and whitesur_dir.stat.isdir
  register: reinstall_white_sur_icon_theme

- name: Clone WhiteSur repo
  ansible.builtin.git:
    repo: https://github.com/vinceliuice/WhiteSur-icon-theme.git
    dest: /tmp/whitesur
  register: whitesur_clone
  when: reinstall_white_sur_icon_theme.user_input|lower == 'y'

- name: Install WhiteSur icon theme
  become: true
  ansible.builtin.command: /tmp/whitesur/install.sh -a -d /usr/share/icons
  when: whitesur_clone.changed

- name: Set custom settings in GDM
  become: true
  ansible.builtin.copy:
    src: '{{ role_path }}/files/gdm/99-custom-settings'
    dest: '/etc/dconf/db/gdm.d'
    owner: root
    group: root
    mode: '644'

- name: Set custom settings in gnome
  become: true
  ansible.builtin.copy:
    src: '{{ role_path }}/files/gnome/99-custom-settings'
    dest: '/etc/dconf/db/local.d/'
    owner: root
    group: root
    mode: '644'

- name: Reset dconf settings
  ansible.builtin.command: dconf reset {{ item }}
  loop:
    - /org/gnome/desktop/background/picture-uri
    - /org/gnome/desktop/background/picture-uri-dark
    - /org/gnome/shell/enabled-extensions

- name: Update dconf
  become: true
  ansible.builtin.command: dconf update
