---
- name: Install add-ons
  become: true
  ansible.builtin.dnf:
    name: '{{ item }}'
    state: present
  loop: '{{ addons }}'

- name: Create config dir
  ansible.builtin.file:
    path: ~/.config
    state: directory
    mode: '0755'

- name: Enable RPM fusion
  include_tasks: rpmfusion.yml

- name: Install fonts
  include_tasks: fonts.yml

- name: Install docker
  include_tasks: docker.yml

- name: Install CLI tools
  include_tasks: cli.yml

- name: Install desktop apps
  include_tasks: desktop.yml

- name: Clean unused apps & configs
  include_tasks: clean.yml

- name: Config gnome
  include_tasks: gnome.yml

- name: Enable remote access
  include_tasks: remote-access.yml

- name: Enable virtual machines
  include_tasks: virtual-machines.yml

- name: Finish message
  ansible.builtin.debug:
    msg: 'Reboot System now!'
