---
cli_tools:
  - bat
  - fd-find
  - fzf
  - htop
  - opentofu
  - neovim
  - nodejs
  - python3-pip
  - python3-neovim
  - ripgrep
  - tmux
  - uv
  - vagrant
  - zoxide
  - zsh

addons:
  - libreoffice-langpack-pt-BR
  - dnf-plugins-core
  - rsms-inter-fonts
  - gnome-shell-extension-blur-my-shell
  - gnome-shell-extension-dash-to-dock
  - gnome-shell-extension-appindicator

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

flatpaks:
  - com.bitwarden.desktop
  - com.discordapp.Discord
  - com.spotify.Client
  - com.transmissionbt.Transmission
  - io.beekeeperstudio.Studio
  - io.ente.auth
  - io.github.fabrialberio.pinapp
  - io.gitlab.adhami3310.Impression
  - org.filezillaproject.Filezilla
  - org.videolan.VLC
  - md.obsidian.Obsidian

desktop_apps:
  - alacritty
  - code
  - ghostty
  - google-chrome-stable
  - gnome-extensions-app
  - gnome-tweaks
  - nautilus-python
  - remmina
  - thunderbird
  - VirtualBox

clean_apps:
  - gnome-boxes
  - gnome-maps
  - rhythmbox
  - mediawriter
  - ptyxis
  - gnome-connections
